[package]
name = "rocket-etag-if-none-match"
version = "0.1.0"
authors = ["Magic Len <len@magiclen.org>"]
repository = "https://github.com/magiclen/rocket-etag-if-none-match"
homepage = "https://magiclen.org/rocket-etag-if-none-match"
keywords = ["rocket", "server", "web", "static"]
categories = ["parsing"]
description= "This crate provides a request guard used for getting `if-none-match` header."
readme = "README.md"
license = "MIT"

[dependencies]
rocket = "0.3.15"