[package]
name = "rocket-etag-if-none-match"
version = "0.3.5"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/rocket-etag-if-none-match"
homepage = "https://magiclen.org/rocket-etag-if-none-match"
keywords = ["rocket", "server", "web", "etag", "http"]
categories = ["parser-implementations"]
description = "This crate provides a request guard used for getting `if-none-match` header."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[badges.travis-ci]
repository = "magiclen/rocket-etag-if-none-match"
branch = "master"

[dependencies]
rocket = "0.4.2"

[dev-dependencies]
chrono = "0.4.6"
lazy_static = "1.2"